#!/bin/sh
rc=0
case "$1" in
    start) 
        echo "Starting lddmodules"
        /usr/bin/module_load faulty
        if [ $? -ne 0 ]; then
            echo "Failed to load module faulty"
            exit 1
        fi
        /usr/bin/scull_load
        if [ $? -ne 0 ]; then
            echo "Failed to load module faulty"
            exit 1
        fi
        insmod /lib/modules/6.1.44/extra/hello.ko
        if [ $? -ne 0 ]; then
            echo "Failed to load module faulty"
            exit 1
        fi
    ;;
    stop)
        echo "Stopping lddmodules"
        rmmod hello.ko
        /usr/bin/scull_unload
        /usr/bin/module_unload faulty
    ;;
    *)
        echo "usage: $0 {start | stop}"
        exit 1        
esac

exit 0
